[package]
name = "mines-rs"
version = "0.1.0"
authors = ["Toby Dimmick <tobydimmick@protonmail.ch>"]

[dependencies]
bson = "0.10.0" # fixed to match mongodb, used by wither
chrono = { version = "^0.4", features = ["serde"] }
hyper-sync = { git = "https://github.com/tobz1000/hyper-sync" }
itertools = "^0.7"
lazy_static = "^1.0"
mersenne_twister = "^1.0"
mongodb = "^0.3"
quickcheck = "^0.6"
rand = "^0.4"
rayon = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
structopt = "^0.2"
wither = "^0.5"