[package]
name = "mines-rs"
version = "0.1.0"
authors = ["Toby Dimmick <tobydimmick@protonmail.ch>"]

[dependencies]
serde = "*"
hyper_serde = "*"
serde_derive = "*"
time = "*"
hyper = "0.11.6"
tokio-core = "*"
futures = "*"
serde_json = "*"