[package]
name = "mines-rs"
version = "0.1.0"
authors = ["Toby Dimmick <tobydimmick@protonmail.ch>"]

[dependencies]
serde = "*"
serde_derive = "*"
chrono = { version = "*", features = ["serde"] }
hyper = "*"
tokio-core = "*"
futures = "*"
serde_json = "*"
itertools = "*"
futures-await = "*"
rand = "*"
mersenne_twister = "*"
wither = { path = "../../wither" } # wither with bson version locked at 0.10.0 to match mongodb, used by wither (!)
bson = "0.10.0" # fixed to match mongodb, used by wither