[package]
name = "mines-rs"
version = "0.1.0"
authors = ["Toby Dimmick <tobydimmick@protonmail.ch>"]

[dependencies]
serde = "*"
serde_derive = "*"
chrono = { version = "*", features = ["serde"] }
hyper = "0.11.6"
tokio-core = "*"
futures = "*"
serde_json = "*"
itertools = { git = "https://github.com/tobz1000/rust-itertools.git", rev = "multi-product" }